# Generated by Django 4.2.4 on 2023-08-17 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company_sys', '0003_alter_employee_age_alter_employee_animal_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='company_id',
            new_name='job_id',
        ),
    ]
