# Generated by Django 4.2.4 on 2023-08-17 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_sys', '0004_rename_company_id_employee_job_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
